const video=document.getElementById('camera'),canvas=document.getElementById('overlay'),ctx=canvas.getContext('2d');
const panel=document.getElementById('panel'),statusEl=document.getElementById('status'),comboEl=document.getElementById('combo'),energyEl=document.getElementById('energy'),hpEl=document.getElementById('hp'),handCountEl=document.getElementById('handCount');
const slashImage=new Image(); slashImage.src='dismantle-vfx.png';
let W=innerWidth,H=innerHeight,dpr=1,combo=0,energy=300,hp=100,slashes=[],handsReady=false,cameraRunning=false,processing=false,lastHands=[],previousIndex=null,pointStarted=null,lastSlashTime=0,fistSince=0,openSince=0,domainSince=0,rctActive=false,domainActive=false,audioCtx=null;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
function updateHud(){comboEl.textContent=combo;energyEl.style.width=`${energy/3}%`;if(hpEl)hpEl.style.width=`${hp}%`;if(handCountEl)handCountEl.textContent=lastHands.length}updateHud();
function beep(freq=180,d=.12){try{audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sawtooth';o.frequency.value=freq;g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function screenPoint(lm){const vw=video.videoWidth||1280,vh=video.videoHeight||720,s=Math.max(W/vw,H/vh),dw=vw*s,dh=vh*s,ox=(W-dw)/2,oy=(H-dh)/2;return{x:ox+(1-lm.x)*dw,y:oy+lm.y*dh}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function ext(lm,tip,pip,mcp){const w=lm[0];return dist(lm[tip],w)>dist(lm[pip],w)*1.08&&dist(lm[tip],lm[mcp])>dist(lm[pip],lm[mcp])*1.04}
function state(lm){const i=ext(lm,8,6,5),m=ext(lm,12,10,9),r=ext(lm,16,14,13),p=ext(lm,20,18,17);const palm=Math.max(dist(lm[0],lm[9]),1),cur=[8,12,16,20].filter(t=>dist(lm[t],lm[0])<palm*1.6).length>=3;return{point:i&&!m&&!r&&!p,open:[i,m,r,p].filter(Boolean).length>=4,fist:cur}}
function spawnSlash(x,y,a){const now=performance.now();if(energy<12||now-lastSlashTime<240)return;energy-=12;combo++;lastSlashTime=now;updateHud();beep(190,.1);const aspect=(slashImage.naturalWidth||2048)/(slashImage.naturalHeight||700),width=Math.min(W*.58,920);slashes.push({x,y,a,born:now,life:430,width,height:width/aspect})}
function drawSlash(s,now){const age=now-s.born;if(age>=s.life)return false;const enter=Math.min(1,age/55),fade=Math.min(1,(s.life-age)/105),scale=.88+.12*enter;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.globalAlpha=enter*fade;ctx.globalCompositeOperation='screen';ctx.drawImage(slashImage,-s.width*scale/2,-s.height*scale/2,s.width*scale,s.height*scale);ctx.restore();return true}
function render(now){ctx.clearRect(0,0,W,H);slashes=slashes.filter(s=>drawSlash(s,now));if(domainActive){ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(W/2,H/2,Math.min(W,H)*.36,0,Math.PI*2);ctx.stroke()}if(rctActive&&previousIndex){const p=previousIndex,g=ctx.createRadialGradient(p.x,p.y,5,p.x,p.y,75);g.addColorStop(0,'rgba(255,255,255,.9)');g.addColorStop(.35,'rgba(230,245,255,.35)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,75,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.6)';ctx.beginPath();ctx.arc(p.x,p.y,35+Math.sin(now/90)*5,0,Math.PI*2);ctx.stroke()}if(previousIndex){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(previousIndex.x,previousIndex.y,4,0,Math.PI*2);ctx.fill()}requestAnimationFrame(render)}requestAnimationFrame(render);
function triggerDomain(){if(domainActive||energy<45)return;domainActive=true;energy-=45;updateHud();beep(80,.35);setTimeout(()=>domainActive=false,5000)}
function onResults(res){const now=performance.now();lastHands=res.multiHandLandmarks||[];updateHud();if(!lastHands.length){previousIndex=null;pointStarted=null;fistSince=openSince=domainSince=0;rctActive=false;return}
if(lastHands.length>=2){if(!domainSince)domainSince=now;if(now-domainSince>550&&!domainActive)triggerDomain()}else domainSince=0;
const lm=lastHands[0],s=state(lm),idx=screenPoint(lm[8]);previousIndex=idx;
if(s.point){fistSince=openSince=0;if(!pointStarted)pointStarted={...idx};const dx=idx.x-pointStarted.x,dy=idx.y-pointStarted.y;if(Math.hypot(dx,dy)>28&&now-lastSlashTime>240){spawnSlash(idx.x,idx.y,Math.atan2(dy,dx));pointStarted={...idx}}}else pointStarted=null;
if(s.fist){openSince=0;if(!fistSince)fistSince=now;if(now-fistSince>220&&energy<300){energy=Math.min(300,energy+1.8);updateHud()}}else fistSince=0;
if(s.open){fistSince=0;if(!openSince)openSince=now;if(now-openSince>180){rctActive=true;if(energy>0){energy=Math.max(0,energy-.9);hp=Math.min(100,hp+.55);updateHud()}else rctActive=false}}else{openSince=0;rctActive=false}}
async function setupHands(){if(!window.Hands){statusEl.textContent='Hand tracker did not load. Refresh the page.';return}const hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:2,modelComplexity:0,minDetectionConfidence:.55,minTrackingConfidence:.5,selfieMode:false});hands.onResults(onResults);handsReady=true;async function loop(){if(cameraRunning&&video.readyState>=2&&!processing){processing=true;try{await hands.send({image:video})}catch(e){console.warn(e)}processing=false}requestAnimationFrame(loop)}loop()}
async function startCamera(){try{if(!handsReady)await setupHands();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960,max:1280},height:{ideal:540,max:720}},audio:false});video.srcObject=stream;await video.play();cameraRunning=true;statusEl.textContent='2-hand tracking ON — Point/Move: Slash • Fist: Recharge • Open Palm: RCT • 2 Hands: Domain'}catch(e){console.error(e);statusEl.textContent='Camera or hand tracking failed. Allow camera permission and refresh.'}}
document.getElementById('start').onclick=startCamera;document.getElementById('test').onclick=()=>spawnSlash(W/2,H/2,Math.random()*Math.PI*2);document.getElementById('hide').onclick=()=>panel.hidden=!panel.hidden;document.getElementById('show').onclick=()=>panel.hidden=false;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')panel.hidden=!panel.hidden});